name: Sinagle volera video

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Create video playlist
        run: |
          printf "file '%s'\n" \
            "$GITHUB_WORKSPACE/videos/1.mp4" \
            > playlist.txt

      - name: Start YouTube Live
        env:
          YOUTUBE_STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          ffmpeg \
            -re \
            -stream_loop -1 \
            -f concat \
            -safe 0 \
            -i playlist.txt \
            -c:v libx264 \
            -preset veryfast \
            -pix_fmt yuv420p \
            -r 30 \
            -g 60 \
            -b:v 4500k \
            -maxrate 4500k \
            -bufsize 9000k \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -f flv \
            "rtmp://a.rtmp.youtube.com/live2/${YOUTUBE_STREAM_KEY}"

